
name: Runnable
# Remove it after test
on: push
# Enable it on default branch
#   workflow_run:
#     workflows: ["CI and CD"]
#     types: 
#       - completed
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test web on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost
      - name: Test API on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost/api
      - name: Test web on host
        run: curl -s --retry 10 --retry-connrefused http://localhost
      - name: Test API on host
        run: curl -s --retry 10 --retry-connrefused http://localhost/api
  kubernetes:
    runs-on: ubuntu-latest
    name: Install MicroK8s
    steps:
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: '1.18/stable'
          addons: '["dns", "rbac", "storage", "registry", "metrics-server"]'
      - name: Test MicroK8s
        run: |
          kubectl get no
          kubectl get pods -A -o wide
