
name: Runnable
on: push
#   workflow_run:
#     workflows: ["CI and CD"]
#     types: 
#       - completed
env:
  APP_NAME: mplatform
        
jobs:
  compose:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}
      - name: Build the stack
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ steps.docker_meta.outputs.version }}
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Test web on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 5 --retry-connrefused http://localhost/api
      - name: Test web on host
        run: curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API on host
        run: curl -s --retry 5 --retry-connrefused http://localhost/api
  microk8s:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: [ '1.20', 1.19, 1.18 ]
    steps:
      - uses: actions/checkout@v2
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: ${{ matrix.k8s }}/stable
          addons: '["ingress"]'
      - name: Test
        run: |
          kubectl get no
          kubectl get pods -A -o wide
      - name: Deploy
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ steps.docker_meta.outputs.version }}
        run: |
          envsubst < kubernetes/simple.test.yaml | kubectl apply -f -
          kubectl get all
          kubectl get ingress
      - name: Test web
        run: curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API
        run: curl -s --retry 5 --retry-connrefused http://localhost/api
      
