
name: Runnable
# Remove it after test
on: push
# Enable it on default branch
#   workflow_run:
#     workflows: ["CI and CD"]
#     types: 
#       - completed
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test web on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API on container network
        run: docker run --network container:mplatform_app_1 appropriate/curl -s --retry 5 --retry-connrefused http://localhost/api
      - name: Test web on host
        run: curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API on host
        run: curl -s --retry 5 --retry-connrefused http://localhost/api
  microk8s:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: [ '1.20', 1.19, 1.18 ]
    steps:
      - uses: actions/checkout@v2
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: ${{ matrix.k8s }}/stable
          addons: '["ingress"]'
      - name: Test
        run: |
          kubectl get no
          kubectl get pods -A -o wide
      - name: Deploy
        run: |
          kubectl apply -f kubernetes/simple.yaml
          kubectl get all
          kubectl get ingress
      - name: Test web
        run: curl -s --retry 5 --retry-connrefused http://localhost
      - name: Test API
        run: curl -s --retry 5 --retry-connrefused http://localhost/api
      
